apiVersion: v1
kind: Namespace
metadata:
  name: gcl-oss-trustyai
  labels:
    app.kubernetes.io/part-of: gcl-oss-evalhub-qualification
---
apiVersion: v1
kind: Namespace
metadata:
  name: gcl-oss-evalhub
  labels:
    app.kubernetes.io/part-of: gcl-oss-evalhub-qualification
    evalhub.trustyai.opendatahub.io/tenant: "true"
